// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/services/:slug": {
    params: {
      "slug": string;
    };
  };
  "/gallery": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/quote": {
    params: {};
  };
  "/thank-you": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/about" | "/services" | "/services/:slug" | "/gallery" | "/projects" | "/contact" | "/quote" | "/thank-you";
  };
  "pages/Home.jsx": {
    id: "pages/Home";
    page: "/";
  };
  "pages/About.jsx": {
    id: "pages/About";
    page: "/about";
  };
  "pages/Services.jsx": {
    id: "pages/Services";
    page: "/services";
  };
  "pages/ServiceDetail.jsx": {
    id: "pages/ServiceDetail";
    page: "/services/:slug";
  };
  "pages/Gallery.jsx": {
    id: "pages/Gallery";
    page: "/gallery";
  };
  "pages/Projects.jsx": {
    id: "pages/Projects";
    page: "/projects";
  };
  "pages/Contact.jsx": {
    id: "pages/Contact";
    page: "/contact";
  };
  "pages/Quote.jsx": {
    id: "pages/Quote";
    page: "/quote";
  };
  "pages/ThankYou.jsx": {
    id: "pages/ThankYou";
    page: "/thank-you";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "pages/Home": typeof import("./src/pages/Home.jsx");
  "pages/About": typeof import("./src/pages/About.jsx");
  "pages/Services": typeof import("./src/pages/Services.jsx");
  "pages/ServiceDetail": typeof import("./src/pages/ServiceDetail.jsx");
  "pages/Gallery": typeof import("./src/pages/Gallery.jsx");
  "pages/Projects": typeof import("./src/pages/Projects.jsx");
  "pages/Contact": typeof import("./src/pages/Contact.jsx");
  "pages/Quote": typeof import("./src/pages/Quote.jsx");
  "pages/ThankYou": typeof import("./src/pages/ThankYou.jsx");
};